sudo: false
dist: xenial
language: rust
os:
  - linux
  - osx
rust:
- stable
- beta
- nightly
env:
  global:
    - WLA_DX_REPO="gekkio/wla-dx"
    - WLA_DX_COMMIT="83e691c59a238aae671381f819d6ccf225b21349"

matrix:
  allow_failures:
  - rust: nightly

addons:
  apt:
    packages:
      cmake
      libsdl2-dev

cache:
  directories:
    - $HOME/bin
    - /home/travis/.cargo

before_cache:
  - rm -rf /home/travis/.cargo/registry

before_install:
- openssl aes-256-cbc -K $encrypted_f29b02af6b5b_key -iv $encrypted_f29b02af6b5b_iv -in .travis/boot_roms.tar.enc -out .travis/boot_roms.tar -d
- tar -C core/bootroms -xvf .travis/boot_roms.tar
- .travis/install_wla-dx.sh
- export PATH=$PATH:$HOME/bin
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2; fi

install:
- cargo build --features include-bootroms --verbose
- make -C tests clean all

script:
- cargo test --features include-bootroms --all --verbose -- --test-threads=1
