name: ci
on:
  pull_request:
  push:
    branches:
    - master
  schedule:
    - cron: "0 0 * * 1"

jobs:
  check:
    name: Run checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry
      - name: Cache cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all
      - name: Clean cache
        run: |
          cargo install --no-default-features --features ci-autoclean cargo-cache
          cargo-cache
  test:
    name: Run tests
    needs: [check]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    env:
      WLA_DX_REPO: vhelin/wla-dx
      WLA_DX_COMMIT: 6ada10b1cd6035e8b58ce5246bf623b73e2704de
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install Ubuntu packages
        run: sudo apt install cmake libudev-dev
        if: runner.os == 'Linux'
      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry
      - name: Cache cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index
      - name: Cache wla-dx
        uses: actions/cache@v1
        with:
          path: ~/bin
          key: ${{ runner.os }}-wla-dx
      - name: Build wla-dx
        run: .github/install_wla-dx.sh
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features include-bootroms --all
      - name: Clean cache
        run: |
          cargo install --no-default-features --features ci-autoclean cargo-cache
          cargo-cache
